version: '3'

services:
  hardware_control:
    image: stage_mover
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    deploy:
      placement:
        constraints:
          - node.role==manager
    # devices:
    #   - "/dev/ttyACM0:/dev/ttyACM0"